
server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://organization-db-server.ccfeqz6ovj7f.us-east-2.rds.amazonaws.com:5432/organizationdb
    username: orgadmin 
    password: orgadmin
  
  jpa:
    properties: 
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    
flyway:
  locations: db/migration
