server:
  port: 8020
  servlet:
    context-path: /vision-service

spring:
  datasource:
    url: jdbc:mysql://visiondbserver:3306/visiondb?allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false

flyway:
  locations: db/migration

aws:
  s3:
    accessId: FIXME
    secretKey: FIXME
    bucketName: FIXME
